<center>
<img src="images/airbnb.png" style="width:150px;">
</center>
<h1 style="font-family: Trebuchet MS; padding: 12px; font-size: 48px; color: #FF5A5F; text-align: center; line-height: 1.25;"><b>Airbnb Booking Analysis</b></h1>
<hr style="border: 1px solid #FF5A5F; background-color: #FF5A5F; width: 100%;">

<h1 style="font-family: Trebuchet MS; padding: 12px; font-size: 32px; color: #FF5A5F; line-height: 1.25;"><b>Purpose of the Analysis :</b></h1>


<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;">This analysis aims to uncover the factors influencing Airbnb prices in New York City, providing insights into the relationships and patterns within various variables. By doing so, our study offers valuable information for both travelers and hosts, along with key insights for Airbnb's business strategy.<span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>Data Exploration and Cleaning Process :</b><span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;">The project began with a thorough exploration and cleaning of the dataset to ensure its readiness for analysis. We started by examining the dataset’s characteristics—such as data types, missing values, and distribution of values—to understand its structure. The cleaning process involved handling inconsistencies, missing values, and any duplicate records, as well as removing outliers. This preparation stage was essential to ensure data quality, which helps prevent potential biases and errors that could impact our findings.</span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>Preparing the Data for Analysis :</b></span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;">Following the initial exploration and cleaning, we finalized the dataset to ensure high quality, making it ready for analysis. This step is crucial, as it provides a solid foundation for accurate results and reliable insights. With the data now ready, we could dive into answering specific research questions, free from distractions caused by errors or inconsistencies.</span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>Data Exploration and Pattern Identification :</b></span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;">With the dataset cleaned and structured, we proceeded to explore and summarize it through descriptive statistics and visualizations. These exploratory steps helped us uncover patterns and trends, as well as relationships among various factors. By developing these insights, we aimed to better understand how different variables interact, the underlying causes of trends, and other influencing factors.</span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>Visualizing Patterns in the Data :</b></span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;">Using data visualization, we explored Airbnb data patterns and trends by creating a range of graphs and charts. Observations and insights were documented alongside each visualization to further explain the findings. This visual approach allowed us to identify meaningful patterns, such as factors influencing prices and availability across neighborhoods.</span>

<h1 style="font-family: Trebuchet MS; padding: 12px; font-size: 32px; color: #FF5A5F; line-height: 1.25;"><b>Problem Statements :</b></h1>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>1. What are the most popular neighborhoods for Airbnb rentals in New York City? How do prices and availability differ across neighborhoods ?</b></span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>2. How has New York City's Airbnb market evolved over time? Are there notable trends in the number of listings, pricing, or occupancy rates ?</b></span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>3. Are there any clear patterns in the types of properties rented on Airbnb in New York City? Are certain property types more popular or tend to be priced higher ?</b></span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>4. Which factors appear to correlate with Airbnb rental prices in New York City ?</b></span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>5. Which areas in New York City offer the best opportunities for property investment at reasonable prices with high booking demand ?</b></span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>6. How do the lengths of stay for Airbnb rentals vary by neighborhood in New York City? Are there neighborhoods that attract longer stays more than others ?</b></span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>7. Is there a relationship between Airbnb rental ratings and prices in New York City? Are higher-priced listings more likely to have better ratings ?</b></span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>8. What are the total and maximum number of reviews for each neighborhood group ?</b></span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>9. Which room types are the most reviewed within each neighborhood group on a monthly basis ?</b></span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>10. Which listings or locations offer the best experience for travelers in New York City ?</b></span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>11. Which locations or properties are ideal for hosts in New York City ?</b></span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>12. How do prices vary across different neighborhood groups in New York City ?</b></span>

<h1 style="font-family: Trebuchet MS; padding: 12px; font-size: 32px; color: #FF5A5F; line-height: 1.25;"><b>Understanding Given Variables :</b></h1>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>id:</b> A unique identifier assigned to each listing in the dataset.</span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>name:</b> The title of the listing, as it appears on Airbnb.</span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>host_id:</b> A unique identifier assigned to each host in the dataset.</span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>host_name:</b> The name of the host, as displayed on Airbnb.</span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>neighbourhood_group:</b> The broader neighborhood area within New York City, such as Manhattan or Brooklyn.</span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>neighbourhood:</b> The specific neighborhood location of the listing.</span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>latitude:</b> The geographical latitude coordinate of the listing.</span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>longitude:</b> The geographical longitude coordinate of the listing.</span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>room_type:</b> The type of accommodation offered, such as an entire home, private room, or shared room.</span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>price:</b> The nightly rental price for the listing, in US dollars.</span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>minimum_nights:</b> The minimum number of nights a guest is required to book.</span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>number_of_reviews:</b> The total number of reviews the listing has received.</span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>reviews_per_month:</b> The average number of reviews the listing receives each month.</span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>calculated_host_listings_count:</b> The total number of listings that a host has on Airbnb.</span>

<span style="font-family: Trebuchet MS; font-size: 18px; color: #FF5A5F; line-height: 1.25;"><b>availability_365:</b> The number of days the listing is available for booking in the upcoming year (365 days).</span>

<h1 style="font-family: Trebuchet MS; padding: 12px; font-size: 32px; color: #FF5A5F; line-height: 1.25;"><b>Import Libraries</b></h1>

In [42]:
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as plt

%matplotlib inline
warnings.filterwarnings('ignore')

<h1 style="font-family: Trebuchet MS; padding: 12px; font-size: 32px; color: #FF5A5F; line-height: 1.25;"><b>Data Exploration & Data Cleaning</b></h1>

In [43]:
airbnb_df = pd.read_csv("dataset/airbnb_nyc_2019.csv")

In [44]:
airbnb_df.head().T

,0,1,2,3,4
id,2539,2595,3647,3831,5022
name,Clean & quiet apt home by the park,Skylit Midtown Castle,THE VILLAGE OF HARLEM....NEW YORK !,Cozy Entire Floor of Brownstone,Entire Apt: Spacious Studio/Loft by central park
host_id,2787,2845,4632,4869,7192
host_name,John,Jennifer,Elisabeth,LisaRoxanne,Laura
neighbourhood_group,Brooklyn,Manhattan,Manhattan,Brooklyn,Manhattan
neighbourhood,Kensington,Midtown,Harlem,Clinton Hill,East Harlem
latitude,40.64749,40.75362,40.80902,40.68514,40.79851
longitude,-73.97237,-73.98377,-73.9419,-73.95976,-73.94399
room_type,Private room,Entire home/apt,Private room,Entire home/apt,Entire home/apt
price,149,225,150,89,80
minimum_nights,1,1,3,1,10
number_of_reviews,9,45,0,270,9
last_review,2018-10-19,2019-05-21,NaN,2019-07-05,2018-11-19
reviews_per_month,0.21,0.38,NaN,4.64,0.1
calculated_host_listings_count,6,2,1,1,1
availability_365,365,355,365,194,0

<span style="font-family: Trebuchet MS; font-size: 24px; color: #FF5A5F; line-height: 1.25;">Now, rename few columns to better understanding of variables</span>

In [45]:
rename_col = {'id':'listing_id','name':'listing_name','number_of_reviews':'total_reviews','calculated_host_listings_count':'host_listings_count'}

In [48]:
airbnb_df = airbnb_df.rename(columns = rename_col)
airbnb_df.head().T

,0,1,2,3,4
listing_id,2539,2595,3647,3831,5022
listing_name,Clean & quiet apt home by the park,Skylit Midtown Castle,THE VILLAGE OF HARLEM....NEW YORK !,Cozy Entire Floor of Brownstone,Entire Apt: Spacious Studio/Loft by central park
host_id,2787,2845,4632,4869,7192
host_name,John,Jennifer,Elisabeth,LisaRoxanne,Laura
neighbourhood_group,Brooklyn,Manhattan,Manhattan,Brooklyn,Manhattan
neighbourhood,Kensington,Midtown,Harlem,Clinton Hill,East Harlem
latitude,40.64749,40.75362,40.80902,40.68514,40.79851
longitude,-73.97237,-73.98377,-73.9419,-73.95976,-73.94399
room_type,Private room,Entire home/apt,Private room,Entire home/apt,Entire home/apt
price,149,225,150,89,80
minimum_nights,1,1,3,1,10
total_reviews,9,45,0,270,9
last_review,2018-10-19,2019-05-21,NaN,2019-07-05,2018-11-19
reviews_per_month,0.21,0.38,NaN,4.64,0.1
host_listings_count,6,2,1,1,1
availability_365,365,355,365,194,0

<span style="font-family: Trebuchet MS; font-size: 24px; color: #FF5A5F; line-height: 1.25;">Checking shape of Dataset</span>

In [49]:
airbnb_df.shape

(48895, 16)

<span style="font-family: Trebuchet MS; font-size: 24px; color: #FF5A5F; line-height: 1.25;">Basic information of Dataset</span>

In [50]:
airbnb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   listing_id           48895 non-null  int64
 1   listing_name         48879 non-null  object
 2   host_id              48895 non-null  int64
 3   host_name            48874 non-null  object
 4   neighbourhood_group  48895 non-null  object
 5   neighbourhood        48895 non-null  object
 6   latitude             48895 non-null  float64
 7   longitude            48895 non-null  float64
 8   room_type            48895 non-null  object
 9   price                48895 non-null  int64
 10  minimum_nights       48895 non-null  int64
 11  total_reviews        48895 non-null  int64
 12  last_review          38843 non-null  object
 13  reviews_per_month    38843 non-null  float64
 14  host_listings_count  48895 non-null  int64
 15  availability_365     48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

<span style="font-family: Trebuchet MS; font-size: 20px; color: #FF5A5F; line-height: 1.25;"><b>NOTE :</b></span>

<span style="font-family: Trebuchet MS; font-size: 20px; color: #FF5A5F; line-height: 1.25;">So, host_name, neighbourhood_group, neighbourhood and room_type fall into categorical variable category.</span>
    
<span style="font-family: Trebuchet MS; font-size: 20px; color: #FF5A5F; line-height: 1.25;">While host_id, latitude, longitude, price, minimum_nights, number_of_reviews, last_review, reviews_per_month, host_listings_count, availability_365 are numerical variables</span>

<span style="font-family: Trebuchet MS; font-size: 24px; color: #FF5A5F; line-height: 1.25;">Check duplicate row in Dataset</span>

In [51]:
airbnb_df = airbnb_df.drop_duplicates()
airbnb_df.count()

listing_id             48895
listing_name           48879
host_id                48895
host_name              48874
neighbourhood_group    48895
neighbourhood          48895
latitude               48895
longitude              48895
room_type              48895
price                  48895
minimum_nights         48895
total_reviews          48895
last_review            38843
reviews_per_month      38843
host_listings_count    48895
availability_365       48895
dtype: int64

<span style="font-family: Trebuchet MS; font-size: 20px; color: #FF5A5F; line-height: 1.25;"><b>NOTE :</b></span>
<span style="font-family: Trebuchet MS; font-size: 20px; color: #FF5A5F; line-height: 1.25;">So, there is no duplicate rows</span>

<span style="font-family: Trebuchet MS; font-size: 24px; color: #FF5A5F; line-height: 1.25;">Checking NULL values in Dataset</span>

In [52]:
airbnb_df.isnull().sum()

listing_id                 0
listing_name              16
host_id                    0
host_name                 21
neighbourhood_group        0
neighbourhood              0
latitude                   0
longitude                  0
room_type                  0
price                      0
minimum_nights             0
total_reviews              0
last_review            10052
reviews_per_month      10052
host_listings_count        0
availability_365           0
dtype: int64

<span style="font-family: Trebuchet MS; font-size: 20px; color: #FF5A5F; line-height: 1.25;"><b>NOTE :</b></span>
<span style="font-family: Trebuchet MS; font-size: 20px; color: #FF5A5F; line-height: 1.25;"><b>host_name</b> and <b>listing_name</b> have not large amount of NULL values, so firstly fill those with some substitutes in both the columns.</span>

In [53]:
airbnb_df['listing_name'].fillna('unknown',inplace=True)
airbnb_df['host_name'].fillna('no_name',inplace=True)

In [54]:
airbnb_df[['host_name','listing_name']].isnull().sum()

host_name       0
listing_name    0
dtype: int64

<span style="font-family: Trebuchet MS; font-size: 20px; color: #FF5A5F; line-height: 1.25;"><b>NOTE :</b></span>
<span style="font-family: Trebuchet MS; font-size: 20px; color: #FF5A5F; line-height: 1.25;">Now, the columns <b>last_review</b> and <b>reviews_per_month</b> have total 10052 null values each.</span>
<span style="font-family: Trebuchet MS; font-size: 20px; color: #FF5A5F; line-height: 1.25;"><b>last_review</b> column is not required for our analysis as compared to <b>number_of_reviews</b> & <b>reviews_per_month</b>. We're good to drop this column.</span>

In [55]:
airbnb_df = airbnb_df.drop(['last_review'], axis=1)

In [56]:
airbnb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   listing_id           48895 non-null  int64
 1   listing_name         48895 non-null  object
 2   host_id              48895 non-null  int64
 3   host_name            48895 non-null  object
 4   neighbourhood_group  48895 non-null  object
 5   neighbourhood        48895 non-null  object
 6   latitude             48895 non-null  float64
 7   longitude            48895 non-null  float64
 8   room_type            48895 non-null  object
 9   price                48895 non-null  int64
 10  minimum_nights       48895 non-null  int64
 11  total_reviews        48895 non-null  int64
 12  reviews_per_month    38843 non-null  float64
 13  host_listings_count  48895 non-null  int64
 14  availability_365     48895 non-null  int64
dtypes: float64(3), int64(7), object(5)
memory usage: 5.6+ MB

<span style="font-family: Trebuchet MS; font-size: 20px; color: #FF5A5F; line-height: 1.25;"><b>NOTE :</b></span>
<span style="font-family: Trebuchet MS; font-size: 20px; color: #FF5A5F; line-height: 1.25;">The <b>reviews_per_month</b> column also containing NULL/NaN values and we can simple put 0 reviews by replacing NAN's</span>

In [57]:
airbnb_df['reviews_per_month'] = airbnb_df['reviews_per_month'].replace(to_replace=np.nan,value=0).astype('int64')

In [58]:
airbnb_df['reviews_per_month'].isnull().sum()

0

<span style="font-family: Trebuchet MS; font-size: 20px; color: #FF5A5F; line-height: 1.25;"><b>NOTE :</b></span>
<span style="font-family: Trebuchet MS; font-size: 20px; color: #FF5A5F; line-height: 1.25;">So, there is no null value now in <b>reviews_per_month</b> column because we replaced NULL/NaN value by 0.</span>

<span style="font-family: Trebuchet MS; font-size: 20px; color: #FF5A5F; line-height: 1.25;">Now check the dataset with no NULL values and totally cleaned and ready to analysis.</span>

In [60]:
airbnb_df.sample(5).T

,17565,614,25918,16131,31064
listing_id,13814049,232612,20705026,13031854,24105281
listing_name,Subway accessible apartment in Brooklyn!,"Lovely pied-à-terre, in an historic building",New Clean Private Room In Flushing,Samaria's Brownstone (Crown Heights),Clean Private room in Manhattan(females only)
host_id,81329032,1217241,137129564,72019599,29582228
host_name,Ashlee,Dee,Bing,Maria,Aki
neighbourhood_group,Brooklyn,Brooklyn,Queens,Brooklyn,Manhattan
neighbourhood,Kensington,Bedford-Stuyvesant,Flushing,Crown Heights,East Harlem
latitude,40.64231,40.68309,40.75224,40.67218,40.79309
longitude,-73.97974,-73.94219,-73.81505,-73.95368,-73.94347
room_type,Private room,Entire home/apt,Private room,Entire home/apt,Private room
price,50,110,49,125,90
minimum_nights,5,3,1,2,4
total_reviews,0,305,77,70,1
reviews_per_month,0,3,3,1,0
host_listings_count,1,1,4,1,1
availability_365,0,231,362,132,6